global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:5000']
    metrics_path: '/api/metrics'

  - job_name: 'frontend'
    static_configs:
      - targets: ['frontend:3000']