version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "0.0.0.0:3000:3000"  # Modified
    environment:
      - REACT_APP_API_URL=http://localhost/api
      - WDS_SOCKET_PORT=0    # Add this for React dev server
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "0.0.0.0:5000:5000"  # Modified
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/myapp
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./backend:/app
    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "0.0.0.0:27017:27017"  # Modified
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "0.0.0.0:6379:6379"  # Modified

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "0.0.0.0:80:80"  # Modified
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "0.0.0.0:9090:9090"  # Modified
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "0.0.0.0:3001:3000"  # Modified
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  mongodb_data:
  prometheus_data:
  grafana_data: